version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ai-society-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ai-society-frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped

  taskbot:
    build:
      context: ./taskbot
    container_name: ai-society-taskbot
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: ai-society-net 