version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: ai-society-backend
    env_file:
      - ./backend/.env # create this file with your production variables
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: ai-society-frontend
    env_file:
      - ./frontend/.env # create this file with env variables like NEXT_PUBLIC_API_BASE_URL
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

  taskbot:
    build:
      context: ./taskbot
    container_name: ai-society-taskbot
    env_file:
      - ./taskbot/.env # place your Discord & OpenAI keys here
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: ai-society-net 