import type { Department, Meeting, Person, Task } from "./types"

export const people: Person[] = [
  { id: "person-1", name: "Jane Smith", avatar: "/placeholder.svg?height=32&width=32" },
  { id: "person-2", name: "Michael Johnson", avatar: "/placeholder.svg?height=32&width=32" },
  { id: "person-3", name: "Sarah Williams", avatar: "/placeholder.svg?height=32&width=32" },
  { id: "person-4", name: "David Lee", avatar: "/placeholder.svg?height=32&width=32" },
  { id: "person-5", name: "Emily Chen", avatar: "/placeholder.svg?height=32&width=32" },
  { id: "person-6", name: "Robert Wilson", avatar: "/placeholder.svg?height=32&width=32" },
]

export const departments: Department[] = [
  "Marketing",
  "Finance",
  "Human Resources",
  "Engineering",
  "Product",
  "Sales",
  "Customer Support",
]

export const tasks: Task[] = [
  {
    id: "task-1",
    title: "Website Redesign Project",
    department: "Marketing",
    assignees: [people[0], people[4]],
    description: "Complete redesign of the company website with new branding guidelines and improved user experience.",
    source: "Marketing Strategy Meeting",
    createdAt: "2023-03-15T10:30:00Z",
    updatedAt: "2023-03-20T14:45:00Z",
    priority: "High",
    dueDate: "2023-05-15",
    status: "In Progress",
    meetingId: "meeting-2",
    subtasks: [
      {
        id: "subtask-1-1",
        title: "Create wireframes",
        assignees: [people[0]],
        priority: "High",
        dueDate: "2023-04-01",
        status: "Completed",
        department: "Marketing",
        description: "Design wireframes for all main pages of the website",
        source: "Design Team Meeting",
        createdAt: "2023-03-16T09:30:00Z",
        updatedAt: "2023-03-25T11:20:00Z",
      },
      {
        id: "subtask-1-2",
        title: "Design mockups",
        assignees: [people[0], people[4]],
        priority: "High",
        dueDate: "2023-04-15",
        status: "In Progress",
        department: "Marketing",
        description: "Create high-fidelity mockups based on approved wireframes",
        source: "Design Team Meeting",
        createdAt: "2023-03-17T14:30:00Z",
        updatedAt: "2023-03-28T10:15:00Z",
      },
      {
        id: "subtask-1-3",
        title: "Develop frontend",
        assignees: [people[3]],
        priority: "Medium",
        dueDate: "2023-05-01",
        status: "Not Started",
        department: "Engineering",
        description: "Implement the frontend based on approved designs",
        source: "Development Sprint Planning",
        createdAt: "2023-03-18T11:45:00Z",
        updatedAt: "2023-03-18T11:45:00Z",
      },
    ],
  },
  {
    id: "task-2",
    title: "Q2 Financial Report",
    department: "Finance",
    assignees: [people[1], people[5]],
    description:
      "Prepare the quarterly financial report including revenue analysis, expense breakdown, and profit margins.",
    source: "CFO Directive",
    createdAt: "2023-03-25T09:15:00Z",
    updatedAt: "2023-03-28T11:20:00Z",
    priority: "Critical",
    dueDate: "2023-04-30",
    status: "In Progress",
    meetingId: "meeting-3",
    subtasks: [
      {
        id: "subtask-2-1",
        title: "Gather financial data",
        assignees: [people[1]],
        priority: "Critical",
        dueDate: "2023-04-05",
        status: "In Progress",
        department: "Finance",
        description: "Collect all financial data from various departments",
        source: "Financial Planning Meeting",
        createdAt: "2023-03-26T08:30:00Z",
        updatedAt: "2023-03-29T14:20:00Z",
      },
      {
        id: "subtask-2-2",
        title: "Analyze revenue streams",
        assignees: [people[5]],
        priority: "High",
        dueDate: "2023-04-10",
        status: "Not Started",
        department: "Finance",
        description: "Analyze revenue streams and identify growth patterns",
        source: "Revenue Analysis Meeting",
        createdAt: "2023-03-27T10:15:00Z",
        updatedAt: "2023-03-27T10:15:00Z",
      },
      {
        id: "subtask-2-3",
        title: "Create presentation",
        assignees: [people[1], people[5]],
        priority: "Medium",
        dueDate: "2023-04-20",
        status: "Not Started",
        department: "Finance",
        description: "Prepare presentation slides for the board meeting",
        source: "Board Meeting Preparation",
        createdAt: "2023-03-28T13:45:00Z",
        updatedAt: "2023-03-28T13:45:00Z",
      },
    ],
  },
  {
    id: "task-3",
    title: "New Employee Onboarding",
    department: "Human Resources",
    assignees: [people[2]],
    description:
      "Coordinate onboarding process for new hires including paperwork, training sessions, and equipment setup.",
    source: "HR Department Meeting",
    createdAt: "2023-03-18T13:45:00Z",
    updatedAt: "2023-03-22T10:30:00Z",
    priority: "Medium",
    dueDate: "2023-04-15",
    status: "In Progress",
    subtasks: [
      {
        id: "subtask-3-1",
        title: "Prepare welcome package",
        assignees: [people[2]],
        priority: "Medium",
        dueDate: "2023-03-30",
        status: "Completed",
        department: "Human Resources",
        description: "Prepare welcome packages for all new hires",
        source: "Onboarding Process Review",
        createdAt: "2023-03-19T09:30:00Z",
        updatedAt: "2023-03-29T15:45:00Z",
      },
      {
        id: "subtask-3-2",
        title: "Schedule training sessions",
        assignees: [people[2]],
        priority: "High",
        dueDate: "2023-04-05",
        status: "In Progress",
        department: "Human Resources",
        description: "Coordinate with department heads to schedule training sessions",
        source: "Training Planning Meeting",
        createdAt: "2023-03-20T11:15:00Z",
        updatedAt: "2023-03-27T16:30:00Z",
      },
      {
        id: "subtask-3-3",
        title: "Set up workstations",
        assignees: [people[3], people[2]],
        priority: "Medium",
        dueDate: "2023-04-10",
        status: "Not Started",
        department: "Human Resources",
        description: "Coordinate with IT to set up workstations for new employees",
        source: "IT Coordination Meeting",
        createdAt: "2023-03-21T14:30:00Z",
        updatedAt: "2023-03-21T14:30:00Z",
      },
    ],
  },
  {
    id: "task-4",
    title: "Product Feature Development",
    department: "Engineering",
    assignees: [people[3], people[4]],
    description: "Develop new features for the product based on customer feedback and market analysis.",
    source: "Product Roadmap Meeting",
    createdAt: "2023-03-10T09:00:00Z",
    updatedAt: "2023-03-25T16:30:00Z",
    priority: "High",
    dueDate: "2023-05-20",
    status: "In Progress",
    meetingId: "meeting-1",
    subtasks: [
      {
        id: "subtask-4-1",
        title: "Design system architecture",
        assignees: [people[3]],
        priority: "High",
        dueDate: "2023-04-05",
        status: "Completed",
        department: "Engineering",
        description: "Design the system architecture for the new features",
        source: "Architecture Planning Meeting",
        createdAt: "2023-03-11T10:30:00Z",
        updatedAt: "2023-04-01T14:15:00Z",
      },
      {
        id: "subtask-4-2",
        title: "Implement backend services",
        assignees: [people[3]],
        priority: "High",
        dueDate: "2023-04-25",
        status: "In Progress",
        department: "Engineering",
        description: "Develop backend services to support the new features",
        source: "Development Sprint Planning",
        createdAt: "2023-03-12T13:45:00Z",
        updatedAt: "2023-03-30T11:20:00Z",
      },
      {
        id: "subtask-4-3",
        title: "Create frontend components",
        assignees: [people[4]],
        priority: "Medium",
        dueDate: "2023-05-10",
        status: "Not Started",
        department: "Engineering",
        description: "Develop frontend components for the new features",
        source: "UI Development Meeting",
        createdAt: "2023-03-13T15:00:00Z",
        updatedAt: "2023-03-13T15:00:00Z",
      },
    ],
  },
  {
    id: "task-5",
    title: "Social Media Campaign Planning",
    department: "Marketing",
    assignees: [people[0]],
    description: "Plan and schedule social media content for the upcoming product launch.",
    source: "Marketing Campaign Review",
    createdAt: "2023-03-19T10:00:00Z",
    updatedAt: "2023-03-21T15:30:00Z",
    priority: "High",
    dueDate: "2023-04-10",
    status: "In Progress",
    meetingId: "meeting-2",
    subtasks: [
      {
        id: "subtask-5-1",
        title: "Content calendar creation",
        assignees: [people[0]],
        priority: "High",
        dueDate: "2023-03-25",
        status: "Completed",
        department: "Marketing",
        description: "Create a content calendar for all social media platforms",
        source: "Content Planning Meeting",
        createdAt: "2023-03-19T11:30:00Z",
        updatedAt: "2023-03-24T09:15:00Z",
      },
      {
        id: "subtask-5-2",
        title: "Graphics design",
        assignees: [people[4]],
        priority: "Medium",
        dueDate: "2023-04-01",
        status: "In Progress",
        department: "Marketing",
        description: "Design graphics for social media posts",
        source: "Design Brief Meeting",
        createdAt: "2023-03-20T13:45:00Z",
        updatedAt: "2023-03-28T16:20:00Z",
      },
    ],
  },
]

export const meetings: Meeting[] = [
  {
    id: "meeting-1",
    title: "Product Development Strategy",
    department: "Product",
    summary:
      "Discussion about the roadmap for Q2, feature prioritization, and resource allocation for the upcoming product releases.",
    time: "2023-03-15T14:00:00Z",
    relatedTaskIds: ["task-4"],
    transcript: [
      {
        id: "line-1-1",
        speaker: "Alex Chen (Product Manager)",
        timestamp: "14:02:15",
        text: "Welcome everyone to our product development strategy meeting. Today we'll be discussing our roadmap for Q2.",
      },
      {
        id: "line-1-2",
        speaker: "Emily Wong (UX Designer)",
        timestamp: "14:05:30",
        text: "I've prepared some user research findings that should help us prioritize features.",
      },
      {
        id: "line-1-3",
        speaker: "David Kim (Engineering Lead)",
        timestamp: "14:10:45",
        text: "Based on our current sprint velocity, I think we need to be realistic about what we can deliver in Q2.",
      },
    ],
  },
  {
    id: "meeting-2",
    title: "Marketing Campaign Review",
    department: "Marketing",
    summary:
      "Analysis of the recent marketing campaign performance, ROI discussion, and planning for the next campaign launch.",
    time: "2023-03-18T11:00:00Z",
    relatedTaskIds: ["task-1", "task-5"],
    transcript: [
      {
        id: "line-2-1",
        speaker: "Jessica Martinez (Marketing Director)",
        timestamp: "11:01:20",
        text: "Let's review the performance metrics from our last campaign and see what we can learn.",
      },
      {
        id: "line-2-2",
        speaker: "Ryan Thompson (Digital Marketing Specialist)",
        timestamp: "11:07:45",
        text: "The conversion rates were higher than expected, especially from the social media channels.",
      },
      {
        id: "line-2-3",
        speaker: "Lisa Johnson (Content Manager)",
        timestamp: "11:15:10",
        text: "I think we should double down on the content types that performed well and adjust our strategy accordingly.",
      },
    ],
  },
  {
    id: "meeting-3",
    title: "Quarterly Budget Review",
    department: "Finance",
    summary: "Review of departmental budgets, expense analysis, and financial planning for the upcoming quarter.",
    time: "2023-03-22T09:30:00Z",
    relatedTaskIds: ["task-2"],
    transcript: [
      {
        id: "line-3-1",
        speaker: "Robert Wilson (CFO)",
        timestamp: "09:32:05",
        text: "Good morning everyone. Today we'll be reviewing our quarterly budget and discussing adjustments for the next quarter.",
      },
      {
        id: "line-3-2",
        speaker: "Amanda Clark (Financial Analyst)",
        timestamp: "09:38:30",
        text: "I've prepared a breakdown of expenses by department, and I've highlighted areas where we exceeded our budget.",
      },
      {
        id: "line-3-3",
        speaker: "Thomas Brown (Operations Director)",
        timestamp: "09:45:15",
        text: "We had some unexpected maintenance costs this quarter, but we should be back on track for Q2.",
      },
    ],
  },
]

// Helper function to get related tasks for a meeting
export function getRelatedTasksForMeeting(meetingId: string): Task[] {
  const meeting = meetings.find((m) => m.id === meetingId)
  if (!meeting) return []

  return tasks.filter((task) => meeting.relatedTaskIds.includes(task.id))
}
