name: Dokploy Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [backend, taskbot]

    steps:
      - uses: actions/checkout@v4

      - name: Map service -> app_id
        id: map
        shell: bash
        run: |
          case "${{ matrix.service }}" in
            backend)  echo "app_id=${{ secrets.DOKPLOY_BACKEND_APP_ID }}"  >> $GITHUB_OUTPUT ;;
            taskbot)  echo "app_id=${{ secrets.DOKPLOY_TASKBOT_APP_ID }}"  >> $GITHUB_OUTPUT ;;
          esac

      - name: Deploy ${{ matrix.service }}
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token:     ${{ secrets.DOKPLOY_AUTH_TOKEN }}
          application_id: ${{ steps.map.outputs.app_id }}
          dokploy_url:    ${{ secrets.DOKPLOY_URL }}
